---
title: "decoupage_classe_uni"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{decoupage_classe_uni}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(statconcepts)
library(ggplot2)
library(dplyr)
library(kableExtra)
library(scales)
jaune_insee <- "#FFC400ff"
bleu_insee <- "#3467AEff"
```

```{r}

#Création d'une fonction qui renvoie un vecteur avec les bornes de classe
calculer_bornes <- function(df,num,nbclass,type_decoup){
  x <- df[,num]
  if (type_decoup == "largeur_fixe"){
    max <- max(x)
    min <- min(x)
    largeur <- (max-min)/nbclass #largeur de chaque tranche
    bornes <- seq(min,max,largeur) #vecteur numérique avec les bornes
  }else if (type_decoup == "quantiles"){
    vect_quantiles <- seq(0,1,1/nbclass)
    bornes <- quantile(x,vect_quantiles)
  }
  return(bornes)
}

#Exemple avec grandile
df <- grandile
x <- "PATRIMOINE"
y <- 5
z <- "quantiles"
calculer_bornes(df,x,y,z)

```
```{r}
# A partir du vecteur numérique avec les bornes de classe, on récupère un tableau avec les classes
tabuler_bornes <- function(num,nbclass,type_decoup){

if (type_decoup == "largeur_fixe") {
      tab <- data.frame(cbind(
        seq(1, nbclass,1),
        num[1:nbclass],
        num[2:(nbclass+1)]
      ))
      colnames(tab) <- c("tranche","borne inf","borne sup")
}else if (type_decoup == "quantiles"){
   tab <- data.frame(cbind(
        seq(0, 1, 1 / nbclass),
        num
      ))
      colnames(tab) <- c("quantile","borne")
      rownames(tab) <- NULL
}
  return(tab)
}

df <- grandile
x <- "REV_DISPONIBLE"
y <- 5
z <- "quantiles"
a <- calculer_bornes(df,x,y,z)
b <- tabuler_bornes(a,y,z)

#Fonction qui formatte un data.frame à partir de la deuxième colonne

kbl(b,digits = c(2,0,0),format = "html",align = "c")
```

```{r}
#Afficher un histogramme à partir du vecteur numérique des classes

afficher_histo3 <- function(df,varnum,nbclass,type_decoup,breaknum){
  a <- dput(breaknum)
ggplot(df)+
  aes(.data[[varnum]])+
  geom_histogram(aes(y = ..density..),breaks=a,color=jaune_insee,fill=bleu_insee)+
  theme_minimal()+
  xlab(varnum)+
  scale_x_continuous(labels = scales::label_number_auto())
}

df <- grandile
x <- "PATRIMOINE"
y <- 20
z <- "largeur_fixe"
a <- calculer_bornes(df,x,y,z)
afficher_histo3(df,x,y,z,a)

```



