---
title: "redistribution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{redistribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(statconcepts)
library(ineq)
library(purrr)
library(dplyr)
```

# Situation initiale (avant modif des inégalités)

## Afficher la courbe de Lorenz

```{r}

# Fonction pour afficher la courbe de Lorenz d'une variable quantitative cumulable
afficher_courbe_lorenz <- function(df,
                                   varnum,
                                   col="darkred",
                                   lwd=4,xlab = "Part cumulée des individus (en %)",
                                   ylab = paste("Part cumulée de",varnum,"(en %)"),
                                   main = " "){
  
  plot(Lc(df[,varnum]),col=col,lwd=lwd,xlab=xlab,ylab=ylab,main=main)
  
}
afficher_courbe_lorenz(grandile,"PATRIMOINE")
afficher_courbe_lorenz(mtcars,"wt")

```

## Calculer les indicateurs de redistribution

```{r}

#Fonction qui renvoie un vecteur numérique avec les valeurs des indicateurs de redistribution
calculer_indicateurs_redistrib <- function(df,var){
 
gini <- ineq(df[,var],type="Gini")
min <- min(df[,var],na.rm = TRUE)
max <- max(df[,var],na.rm = TRUE)
rid <- quantile(df[,var],0.9,na.rm = TRUE)/quantile(df[,var],0.1,na.rm = TRUE)
names(rid) <- ""
median <- median(df[,var],na.rm = TRUE)
c("Indice de Gini" = gini,"Minimum" = min,"Maximum" = max,"Rapport inter-décile" = rid,"Médiane" = median)

  
}

calculer_indicateurs_redistrib(grandile,"REV_DISPONIBLE")

```

## Formater les indicateurs

```{r}

x <- calculer_indicateurs_redistrib(grandile,"REV_DISPONIBLE")
y <-formater_indicateurs1(x)
y

```


# Situation après modifications des inégalités

## Afficher la courbe de Lorenz

```{r}

#Création d'une fonction qui prend un df et une variable en entrée et qui renvoie
#un vecteur numérique après redistribution des revenus (augmentation ou diminution
#des inégalités)

modifier_repartition <- function(df,slideinput,dimin=TRUE,tx){
  x <- df[,slideinput]
  varnum <- sort(x)
  if(dimin==TRUE){
ecart_varnum <- varnum - mean(varnum,na.rm = TRUE)
varnum_apresmodif <- varnum - ecart_varnum*(tx/100)
varnum_apresmodif
  }else{
n <- length(varnum)
a <- varnum[1:n-1] #Les n-1 ménages les plus pauvres dont le revenu va être amputé
b <- varnum[n] #Le ménage le plus riche qui prélève le revenu des autres
varnum_apresmodif <- (1 - tx/100)*a #revenu des plus pauvres après augmentation des inégalités
b <- b + sum(a)-sum(varnum_apresmodif) #augmentation du revenu du plus riche qui prend tous les prélèvements
varnum_apresmodif[n] <- b
varnum_apresmodif
  }
}

x <- modifier_repartition(grandile,"REV_DISPONIBLE",dimin = FALSE,tx=100)
plot(Lc(x),col="darkred",lwd=5)



#courbe de Lorenz après modifications de la répartition

#Diminution
plot(Lc(varnum_apresred))
#Augmentation
plot(Lc(varnum_apresaug))

#Calcul des indicateurs après modification de la répartition
ineq(varnum_apresred)
ineq(varnum)


```

## Calculer les indicateurs


