---
title: "valeurs_extremes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{valeurs_extrêmes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(statconcepts)
library(ggplot2)
library(dplyr)
```

# Afficher un histogramme

```{r}

#Création d'une fonction qui affiche un histogramme
#La fonction prend deux inputs au format caractère (une data et une variable) et renvoie un objet ggplot
afficher_histo1 <- function(df,var){
  ggplot(df) + aes(x = .data[[var]]) + geom_histogram(col="black",fill="lightblue",bins = 20) + theme_minimal()
}

afficher_boxplot1 <- function(df,var){
  ggplot(df) + 
    aes(x = .data[[var]]) + 
    geom_boxplot(col="black",fill="lightblue") + 
    coord_flip()+ 
    theme_minimal()
}

afficher_histo1(mtcars,"mpg")
afficher_boxplot1(mtcars,"mpg")
afficher_histo1(grandile,"PATRIMOINE")
afficher_boxplot1(grandile,"PATRIMOINE")
```

# Calculer les 4 indicateurs

```{r}
#La fonction prend un dataframe et une variable au format caractère en input
#pour renvoyer un vecteur numérique de 4 éléments
calculer_indicateurs1 <- function(df,var){
  moy <- mean(df[,var],na.rm=FALSE)
  med <- median(df[,var],na.rm=FALSE)
  sd <- sd(df[,var],na.rm=FALSE)
  cv <- sd/moy*100
  c("Moyenne"=moy,"Médiane"=med,"Ecart-type" = sd,"Coeff de variation (en %)"=cv) 
}

formater_indicateurs1 <-function(vec){
  vec %>% round(1) %>% format(big.mark = " ",decimal.mark = ",",nsmall=1)
} 

calculer_indicateurs1(grandile,"PATRIMOINE")

calculer_indicateurs1(mtcars,"mpg")

```

# Base de données avec des valeurs extrêmes

```{r}

#Création d'une fonction qui prend un vecteur numérique en entrée et qui renvoie un vecteur numérique
# avec n valeurs extrêmes en plus
ajouter_valeurs_extremes <- function(df,num,sup=TRUE,nb){
  a <- df[,num] #vecteur numérique
  #Calcul des seuils supérieurs et inférieurs
q3 <- quantile(a,0.75)
q1 <- quantile(a,0.25)
seuil_sup <- q3 + 1.5*(q3-q1)
seuil_inf <- q1 - 1.5*(q3-q1)
n <- nb #nombre de valeurs extrêmes à générer
#génération de valeurs extrêmes supérieures et inférieures
  if (sup){
 
b <- rnorm(n,4*seuil_sup,seuil_sup)
  }else{
b <- rnorm(n,4*seuil_inf,abs(seuil_inf))
  }

#Nouveau vecteur après ajout de valeurs extrêmes
return(c(a,b))

}

ajouter_valeurs_extremes(mtcars,"disp",nb=10)
```

# Comparaison des indicateurs avant et après ajout de valeurs extrêmes

```{r}
calculer_indicateurs2 <- function(num){
  moy <- mean(num,na.rm=FALSE)
  med <- median(num,na.rm=FALSE)
  sd <- sd(num,na.rm=FALSE)
  cv <- sd/moy*100
  c("Moyenne"=moy,"Médiane"=med,"Ecart-type" = sd,"Coeff de variation (en %)"=cv) 
}

#Exemple avec mtcars (peu d'individus)
a <- ajouter_valeurs_extremes(mtcars,"disp",nb=1)
calculer_indicateurs2(a)
calculer_indicateurs1(mtcars,"disp")

#Exemple avec grandile
b <- ajouter_valeurs_extremes(grandile,"REV_DISPONIBLE",nb=100)
calculer_indicateurs2(b) %>% formater_indicateurs1()
calculer_indicateurs1(grandile,"REV_DISPONIBLE") %>% formater_indicateurs1()
```

# Génération de l'histogramme après ajout de valeurs extrêmes

```{r}

#Fonction qui génère un histogramme à partir du vecteur numérique avec les valeurs
# extrêmes et du nom de la variable

afficher_histo2 <- function(inputselect,num){
  c <- num %>% as.data.frame()
names(c) <- inputselect
ggplot(c) + 
  aes(x = .data[[inputselect]]) + 
  geom_histogram(col="black",fill="lightgreen",bins = 20) +
  theme_minimal()
}

afficher_boxplot2 <- function(inputselect,num){
  c <- num %>% as.data.frame()
names(c) <- inputselect
ggplot(c) + 
  aes(x = .data[[inputselect]]) + 
  geom_boxplot(col="black",fill="lightgreen") +
  coord_flip()+
  theme_minimal()
}


b <- ajouter_valeurs_extremes(grandile,"REV_DISPONIBLE",nb=1)
afficher_histo1(grandile,"REV_DISPONIBLE")
afficher_histo2("REV_DISPONIBLE",b)
afficher_boxplot1(grandile,"REV_DISPONIBLE")
afficher_boxplot2("REV_DISPONIBLE",b)

```

